# Generated by Django 3.0 on 2022-09-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220916_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursus',
            name='cursus',
            field=models.CharField(default=False, max_length=30),
            preserve_default=False,
        ),
    ]
