# Generated by Django 3.0 on 2022-09-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cursus_cursus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTrainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
