# Generated by Django 3.0 on 2022-09-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_personaltrainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasAanvraag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=30)),
                ('achternaam', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('adres', models.CharField(max_length=30)),
            ],
        ),
    ]
